name: counter
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dart_web_components:
    path: ../../
  js: ^0.6.7
  web: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.7
  lints: ^3.0.0
